# Generated by Django 3.1.7 on 2021-04-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narmeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday',
            name='dinner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='monday',
            name='lunch',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
