# Generated by Django 3.1.7 on 2021-04-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narmeal', '0002_auto_20210427_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday',
            name='dinner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monday',
            name='lunch',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
