# Generated by Django 3.1.7 on 2021-04-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narmeal', '0004_auto_20210427_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
            ],
        ),
    ]
