# Generated by Django 3.1.7 on 2021-04-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narmeal', '0005_friday_saturday_sunday_thursday_wednesday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friday',
            name='dinner',
            field=models.CharField(default='Nothing yet', max_length=200),
        ),
        migrations.AlterField(
            model_name='friday',
            name='lunch',
            field=models.CharField(default='Nothing yet', max_length=200),
        ),
    ]
