# Generated by Django 3.1.7 on 2021-04-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narmeal', '0006_auto_20210428_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friday',
            name='dinner',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='friday',
            name='lunch',
            field=models.CharField(max_length=200),
        ),
    ]
