# Generated by Django 3.1.7 on 2021-04-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narmeal', '0007_auto_20210428_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(max_length=200),
        ),
    ]
